@startuml
actor       User       as user
participant StoryDetailView as view
participant InteractionsController as interact
participant MsgService as msgService
database    Database as db

user -> view ++: 1. Click like/follow
view -> interact ++ : 2. Request API
interact -> interact ++ : 3. Process method
interact -> db ++ : 4.Query data
db --> interact -- : 5. Return
interact -> msgService ++-- : 6. MsgReturn()
deactivate interact
msgService --> view -- : 7. Response Payload Format
view --> user -- : 8. Display Story Detail Page
@enduml


