@startuml
actor       Author       as user
participant StoryPublishView as view

participant StoriesController as controller

participant MsgService as msgService
database    Database as db

user -> view ++: 1. Click edit story
alt params edit
    user -> view : 2. Edit parameters
    view -> controller ++ : 3. Request API
    controller -> controller ++ : 4. Process SaveStory()
    controller -> db ++ : 5.Query data
    db --> controller -- : 6. Return
    controller -> view -- : 7. Response Payload Format
    deactivate controller
else
    user -> view : 2. Change Story cover
    view -> controller ++ : 3. Request API
    controller -> controller ++ : 4. Process ChangeStoryImage()
    controller -> db ++ : 5.Query data
    db --> controller -- : 6. Return
    controller -> view -- : 7. Response Payload Format
    deactivate controller
end
view --> user -- : 8. Display Stories Management Page


@enduml


