@startuml
actor       User       as user
participant StoryManagementView as view

participant ChaptersController as controller

participant MsgService as msgService
database    Database as db

user -> view ++: 1. Click Edit Vpolume
user -> view : 2. Fill title
view -> controller ++ : 3. Request API
controller -> controller ++ : 4. Process UpdateVolume()
controller -> db ++ : 5.Query data
db --> controller -- : 6. Return
controller -> view -- : 7. Response Payload Format
deactivate controller
view --> user -- : 8. Display Stories Management Page


@enduml


