@startuml
actor       User       as user
participant WalletView as view

participant TransactionsController as controller

participant MsgService as msgService
database    Database as db

user -> view ++: 1. Click wallet nav
view -> controller ++ : 2. Request API
controller -> controller ++ : 3. Process GetUserWallet()
controller -> db ++ : 4.Query data
db --> controller -- : 5. Return data
controller -> msgService ++-- : 6. MsgReturn()
deactivate controller
msgService --> view -- : 7. Response Payload Format
view --> user -- : 8. Display Wallet Page


@enduml


