@startuml
actor       User       as user
participant WalletView as view

participant TicketsController as controller

participant MsgService as msgService
database    Database as db

user -> view ++: 1. Click refund
user -> view : 2. Fill params request
view -> controller ++ : 3. Request API
controller -> controller ++ : 4. Process SendRefund()
controller -> db ++ : 5.Query data
db --> controller -- : 6. Return
controller -> msgService ++-- : 7. MsgActionReturn()
deactivate controller
msgService --> view -- : 8. Response Payload Format
view --> user -- : 9. Display Wallet Page


@enduml


