@startuml
actor       Admin       as user
participant UserManagelView as view
participant UsersController as story
participant MsgService as msgService
database    Database as db

user -> view ++: 1. Click user management
view -> story ++ : 2. Request API
story -> story ++ : 3. Process GetAllUsers()
story -> db ++ : 4.Query data
db --> story -- : 5. Return data
story -> msgService ++-- : 6. MsgReturn()
deactivate story
msgService --> view -- : 7. Response Payload Format

view --> user -- : 8. Display Users Management Page

@enduml


